server:
  port: 80
  error:
    include-message: always
    include-stacktrace: on_param
spring:
  datasource:
    url: jdbc:h2:./db/library;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    show-sql: true
#    schema: classpath:sql/schema.sql
#    initialization-mode: always

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8082
  address: 10.92.92.22

---
spring:
  config:
    activate:
      on-profile: int-test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    show-sql: true
    generate-ddl: true

logging:
  level:
    org.springframework.test: ERROR
    org.springframework.boot.test: ERROR
