server:
  port: 80
  error:
    include-message: always
    include-stacktrace: on_param
spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: xxx
    password: xxx
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate.jdbc.batch_size: 100
      hibernate.jdbc.fetch_size: 100
      hibernate.order_inserts: true
      hibernate.generate_statistics: false
  security:
    secret: 2c71790a-875e-469c-bab6-b66af9ac2641
    token:
      exp: 10 #minutes
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: HS256
          jwk-set-uri: http://koldyr.com/.well-known/jwk.json
  jackson:
    default-property-inclusion: non_null

#    schema: classpath:sql/schema.sql
#    initialization-mode: always

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: int-test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=true
    username: xxx
    password: xxx
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    generate-ddl: true
  test:
    user: xxx
    password: xxx

logging:
  level:
    org.springframework.test: ERROR
    org.springframework.boot.test: ERROR
