server:
  port: 80
  error:
    include-message: always
    include-stacktrace: on_param
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: xxx
    password: xxx
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  security:
    secret: kdskliojfsdl32r3hhkjdfdf
    token:
      exp: 10 #minutes
  jackson:
    default-property-inclusion: non_null

#    schema: classpath:sql/schema.sql
#    initialization-mode: always

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: int-test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=true
    username: xxx
    password: xxx
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true

logging:
  level:
    org.springframework.test: ERROR
    org.springframework.boot.test: ERROR

library:
  test:
    user: xxx
    password: xxx
