### Get Authors
GET http://{{server}}/api/v1/authors
Authorization: Bearer {{token}}
Accept: application/json

### Get Author
GET http://{{server}}/api/v1/authors/1
Authorization: Bearer {{token}}
Accept: application/json

### Create Author
POST http://{{server}}/api/v1/authors
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "firstName": "a5_first",
  "lastName": "a5_last",
  "dateOfBirth": "1994-10-10"
}

### Update Author
PUT http://{{server}}/api/v1/authors/3
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "firstName": "a3_first",
  "lastName": "a3_last",
  "dateOfBirth": "1993-12-12"
}

### Delete Author
DELETE http://{{server}}/api/v1/authors/2
Authorization: Bearer {{token}}

### Get all Author's books
GET http://{{server}}/api/v1/authors/4/books
Authorization: Bearer {{token}}
