### Get Authors
GET http://localhost/api/library/authors
Authorization: Basic {{BasicHash}}
Accept: application/json

### Get Author
GET http://localhost/api/library/authors/1
Authorization: Basic {{BasicHash}}
Accept: application/json

### Create Author
POST http://localhost/api/library/authors
Authorization: Basic {{BasicHash}}
Content-Type: application/json
Accept: application/json

{
  "firstName": "a5_first",
  "lastName": "a5_last",
  "dateOfBirth": "1994-10-10"
}

### Update Author
PUT http://localhost/api/library/authors/3
Authorization: Basic {{BasicHash}}
Content-Type: application/json
Accept: application/json

{
  "firstName": "a3_first",
  "lastName": "a3_last",
  "dateOfBirth": "1993-12-12"
}

### Delete Author
DELETE http://localhost/api/library/authors/2
Authorization: Basic {{BasicHash}}

### Get all Author's books
GET http://localhost/api/library/authors/4/books
Authorization: Basic {{BasicHash}}
