### Get Books
GET http://{{server}}/library/books
Authorization: Bearer {{token}}
Accept: application/json

### Get Book
GET http://{{server}}/library/books/1
Authorization: Bearer {{token}}
Accept: application/json

### Create Book
POST http://{{server}}/library/books
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "title": "b5_title",
  "authorId": 4,
  "genre": "MYSTERY",
  "publishingHouse": "b5_house",
  "publicationDate": "2021-05-09",
  "bookCover": null,
  "note": "b5_note",
  "count": 10
}

### Update Book
PUT http://{{server}}/library/books/1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "title": "b1_title",
  "authorId": 1,
  "genre": "CRIME",
  "publishingHouse": "b1_house",
  "publicationDate": "2021-09-09",
  "bookCover": null,
  "note": "b1_note",
  "count": 10
}

### Delete Book
DELETE http://{{server}}/library/books/1
Authorization: Bearer {{token}}

### Get all Books of Author
GET http://{{server}}/library/authors/1/books
Authorization: Bearer {{token}}

### Search Books
POST http://{{server}}/library/books/search
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "title": "b3",
  "sort": {
    "order": "DESC",
    "name": "title"
  }
}

### Take Book
POST http://{{server}}/library/books/take
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "bookId": 5,
  "readerId": 1,
  "notes": "o2_note"
}

### Return Book
POST http://{{server}}/library/books/return
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "id": 103,
  "notes": "o103_note_returned"
}

### Feedback on Book
POST http://{{server}}/library/books/feedback
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "readerId": 1,
  "bookId": 3,
  "text": "b3_feedback",
  "rate": 9
}

### Get all Feedbacks for Book
GET http://{{server}}/library/books/5/feedbacks
Authorization: Bearer {{token}}

### Get all Feedbacks for Book
GET http://{{server}}/library/books/3/orders
Authorization: Bearer {{token}}
