### Get Books
GET http://localhost:8080/api/library/books
Accept: application/json

### Get Book
GET http://localhost:8080/api/library/books/1
Accept: application/json

### Create Book
POST http://localhost:8080/api/library/books
Content-Type: application/json
Accept: application/json

{
  "title": "b4_title",
  "authorId": 4,
  "genre": "MYSTERY",
  "publishingHouse": "b4_house",
  "publicationDate": "2021-04-09",
  "bookCover": null,
  "note": "b4_note",
  "count": 10
}

### Update Book
PUT http://localhost:8080/api/library/books/1
Content-Type: application/json
Accept: application/json

{
  "title": "b1_title",
  "authorId": 1,
  "genre": "CRIME",
  "publishingHouse": "b1_house",
  "publicationDate": "2021-09-09",
  "bookCover": null,
  "note": "b1_note",
  "count": 10
}

### Delete Book
DELETE http://localhost:8080/api/library/books/1

### Get all Feedbacks for Book
GET http://localhost:8080/api/library/books/1/feedbacks

### Get all Books of Author
GET http://localhost:8080/api/library/authors/2/books

### Search Books
POST http://localhost:8080/api/library/books/search
Content-Type: application/json
Accept: application/json

{
  "publishYearFrom": 2000,
  "publishYearTill": 2030
}

### Take Book
POST http://localhost:8080/api/library/books/2/take
Content-Type: application/json
Accept: application/json

{
  "readerId": 2,
  "note": "o2_note"
}

### Return Book
POST http://localhost:8080/api/library/books/3/return
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "note": "o1_note_returned"
}

### Feedback on Book
POST http://localhost:8080/api/library/books/1/feedback
Content-Type: application/json
Accept: application/json

{
  "readerId": 1,
  "bookId": 1,
  "text": "f1_feedback",
  "rate": 6
}
