### Get Books
GET http://localhost:8080/api/library/books
Accept: application/json

### Get Book
GET http://localhost:8080/api/library/books/1
Accept: application/json

### Create Book
POST http://localhost:8080/api/library/books
Content-Type: application/json
Accept: application/json

{
  "title": "b3_title",
  "authorId": 3,
  "genre": "DETECTIVE",
  "publishingHouse": "b3_house",
  "publicationDate": "2021-09-09",
  "bookCover": null,
  "note": "b3_note",
  "count": 10
}

### Update Book
PUT http://localhost:8080/api/library/books/1
Content-Type: application/json
Accept: application/json

{
  "title": "b32_title",
  "authorId": 1,
  "genre": "CRIME",
  "publishingHouse": "b32_house",
  "publicationDate": "2021-09-09",
  "bookCover": null,
  "note": "b32_note",
  "count": 20
}

### Delete Book
DELETE http://localhost:8080/api/library/books/1

### Get all Feedbacks for Book
GET http://localhost:8080/api/library/books/1/feedbacks

### Get all Books of Author
GET http://localhost:8080/api/library/authors/1/books

### Search Books
POST http://localhost:8080/api/library/books/search
Content-Type: application/json
Accept: application/json

{
  "publishYearFrom": 2000,
  "publishYearTill": 2030
}
