GET http://localhost:8080/api/library/readers

###
GET http://localhost:8080/api/library/readers/6
Accept: application/json

### Create Reader
POST http://localhost:8080/api/library/readers
Content-Type: application/json
Accept: application/json

{
  "firstName": "r1_first",
  "lastName": "r1_last",
  "mail": "r1_mail",
  "address": "r1_address",
  "phoneNumber": "r1-111-222-333",
  "note": "r1_note"
}

### Update Reader
PUT http://localhost:8080/api/library/readers/4
Content-Type: application/json
Accept: application/json

{
  "firstName": "r1_first",
  "lastName": "r1_last",
  "mail": "r1_mail",
  "address": "r1_address",
  "phoneNumber": "r1-111-222-333",
  "note": "r1_note"
}

### Delete Reader
DELETE http://localhost:8080/api/library/readers/1


###
GET http://localhost:8080/api/library/readers/1/orders
Accept: application/json


### Get Books
GET http://localhost:8080/api/library/books
Accept: application/json

### Get Book
GET http://localhost:8080/api/library/books/1
Accept: application/json

### Create Book
POST http://localhost:8080/api/library/books
Content-Type: application/json
Accept: application/json

{
  "husband": 1,
  "wife": 2
}

### Update Book
POST http://localhost:8080/api/library/books/1
Content-Type: application/json
Accept: application/json

{
  "husband": 1,
  "wife": 2
}

### Delete Book
POST http://localhost:8080/api/library/books/1
