GET http://localhost:8080/api/library/readers

###
GET http://localhost:8080/api/library/readers/6
Accept: application/json

### Create Reader
POST http://localhost:8080/api/library/readers
Content-Type: application/json
Accept: application/json

{
  "name": {
    "first": "p5_name",
    "middle": "p5_middle",
    "last": "p5_last"
  },
  "gender": "MALE",
  "place": "p5_place",
  "occupation": "p5_occup",
  "note": "p5_note"
}

### Update Reader
PUT http://localhost:8080/api/library/readers/4
Content-Type: application/json
Accept: application/json

{
  "name": {
    "first": "p5_name",
    "middle": "p5_middle",
    "last": "p5_last"
  },
  "gender": "FEMALE",
  "place": "p5_place",
  "occupation": "p5_occup",
  "note": "p5_note"
}

### Delete Reader
DELETE http://localhost:8080/api/library/readers/1

### Get Books
GET http://localhost:8080/api/library/books
Accept: application/json

### Get Book
GET http://localhost:8080/api/library/books/1
Accept: application/json

### Create Book
POST http://localhost:8080/api/library/books
Content-Type: application/json
Accept: application/json

{
  "husband": 1,
  "wife": 2
}

### Update Book
POST http://localhost:8080/api/library/books/1
Content-Type: application/json
Accept: application/json

{
  "husband": 1,
  "wife": 2
}

### Delete Book
POST http://localhost:8080/api/library/books/1
