### Register User
POST http://{{server}}/library/registration
Content-Type: application/json

{
  "firstName": "r7_first",
  "lastName": "r7_last",
  "mail": "r7_mail@server.com",
  "password": "r7_first",
  "address": "r7_address",
  "phoneNumber": "r7-444-444-444",
  "note": "r7_note",
  "roles": [
    "librarian"
  ]
}

### User Login
POST http://{{server}}/library/login
Content-Type: application/json

{
  "username": "me@koldyr.com",
  "password": "{{testUserPwd}}"
}

### Get All Readers
GET http://{{server}}/library/readers
Authorization: Bearer {{token}}

### Get All Readers
GET http://{{server}}/library/readers
Authorization: Bearer {{token}}

### Get Specific Reader
GET http://{{server}}/library/readers/1
Authorization: Bearer {{token}}
Accept: application/json

### Update Reader
PUT http://{{server}}/library/readers/3
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "firstName": "r4_first",
  "lastName": "r4_last",
  "mail": "r4_mail",
  "address": "r4_address",
  "phoneNumber": "r4-111-222-333",
  "note": "r4_note"
}

### Delete Reader
DELETE http://{{server}}/library/readers/1
Authorization: Bearer {{token}}

### Reader Orders
GET http://{{server}}/library/readers/1/orders?returned=false
Authorization: Bearer {{token}}
Accept: application/json

### Reader Feedbacks
GET http://{{server}}/library/readers/1/feedbacks
Authorization: Bearer {{token}}
Accept: application/json
