name: Build All & Test

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sources checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
              java-version: '11'
              distribution: 'adopt'
              cache: 'maven'
      - name: Build All
        run: mvn -B package -DskipTests --file pom.xml
      - name: Test All
        run: mvn -B test -Dspring.profiles.active=int-test --file pom.xml
