alter table T_BOOK drop constraint FK_BOOK_AUTHOR;
alter table T_ORDER drop constraint FK_ORDER_BOOK;
alter table T_ORDER drop constraint FK_ORDER_READER;
alter table T_FEEDBACK drop constraint FK_FEEDBACK_BOOK;
alter table T_FEEDBACK drop constraint FK_FEEDBACK_READER;

DROP TABLE T_ROLE_PRIVILEGES;
DROP TABLE T_READER_ROLES;
DROP TABLE T_BOOK;
DROP TABLE T_READER;
DROP TABLE T_ORDER;
DROP TABLE T_AUTHOR;
DROP TABLE T_FEEDBACK;
DROP TABLE T_ROLE;
DROP TABLE T_PRIVILEGE;

DROP SEQUENCE SEQ_BOOK;
DROP SEQUENCE SEQ_READER;
DROP SEQUENCE SEQ_ORDER;
DROP SEQUENCE SEQ_AUTHOR;
DROP SEQUENCE SEQ_FEEDBACK;
